import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { Client, Fournisseur, Produit, PurchaseOrder, StockMovement, Vente } from '../models/types';
import { MOCK_CLIENTS, MOCK_MOVEMENTS, MOCK_ORDERS, MOCK_PRODUCTS, MOCK_SALES, MOCK_SUPPLIERS } from '../data/mock-data';

@Injectable({ providedIn: 'root' })
export class DemoStoreService {
  private readonly prefix = 'reda-auto-demo-';
  private productsSubject = new BehaviorSubject(this.load<Produit[]>('products', MOCK_PRODUCTS));
  private clientsSubject = new BehaviorSubject(this.load<Client[]>('clients', MOCK_CLIENTS));
  private suppliersSubject = new BehaviorSubject(this.load<Fournisseur[]>('suppliers', MOCK_SUPPLIERS));
  private salesSubject = new BehaviorSubject(this.load<Vente[]>('sales', MOCK_SALES));
  private movementsSubject = new BehaviorSubject(this.load<StockMovement[]>('movements', MOCK_MOVEMENTS));
  private ordersSubject = new BehaviorSubject(this.load<PurchaseOrder[]>('orders', MOCK_ORDERS));
  products$ = this.productsSubject.asObservable(); clients$ = this.clientsSubject.asObservable(); suppliers$ = this.suppliersSubject.asObservable(); sales$ = this.salesSubject.asObservable(); movements$ = this.movementsSubject.asObservable(); orders$ = this.ordersSubject.asObservable();
  get products(): Produit[] { return this.productsSubject.value; } get clients(): Client[] { return this.clientsSubject.value; } get suppliers(): Fournisseur[] { return this.suppliersSubject.value; } get sales(): Vente[] { return this.salesSubject.value; } get movements(): StockMovement[] { return this.movementsSubject.value; } get orders(): PurchaseOrder[] { return this.ordersSubject.value; }
  upsertProduct(product: Produit): void { const items = [...this.products]; const index = items.findIndex(item => item.id === product.id); const value = index < 0 ? { ...product, id: Date.now(), reference: product.reference || `RA-${Date.now().toString().slice(-4)}` } : product; index < 0 ? items.unshift(value) : items.splice(index, 1, value); this.save('products', items, this.productsSubject); }
  removeProduct(id: number): void { this.save('products', this.products.filter(item => item.id !== id), this.productsSubject); }
  getProduct(id: number): Produit | undefined { return this.products.find(item => item.id === id); }
  upsertClient(client: Client): void { const items = [...this.clients]; const index = items.findIndex(item => item.id === client.id); const value = index < 0 ? { ...client, id: Date.now() } : client; index < 0 ? items.unshift(value) : items.splice(index, 1, value); this.save('clients', items, this.clientsSubject); }
  removeClient(id: number): void { this.save('clients', this.clients.filter(item => item.id !== id), this.clientsSubject); }
  createSale(sale: Vente): void { sale.items.forEach(line => { const product = this.getProduct(line.produitId); if (!product || product.stock - product.stockReserve < line.qte) throw new Error(`Stock insuffisant pour ${line.nom}`); product.stock -= line.qte; this.addMovement({ id: Date.now() + line.produitId, date: sale.date, type: 'VENTE', produitId: product.id, reference: product.reference, produitNom: product.nom, quantite: -line.qte, stockApres: product.stock, motif: 'Vente comptoir', document: sale.numero, utilisateur: sale.vendeur }); }); this.save('products', [...this.products], this.productsSubject); this.save('sales', [sale, ...this.sales], this.salesSubject); }
  adjustStock(productId: number, quantity: number, motif: string): void { const product = this.getProduct(productId); if (!product) return; product.stock = Math.max(0, product.stock + quantity); this.save('products', [...this.products], this.productsSubject); this.addMovement({ id: Date.now(), date: new Date().toISOString(), type: 'CORRECTION', produitId: product.id, reference: product.reference, produitNom: product.nom, quantite: quantity, stockApres: product.stock, motif, document: `COR-${Date.now().toString().slice(-6)}`, utilisateur: localStorage.getItem('username') || 'admin' }); }
  refundSale(saleId: number): void { const sales=[...this.sales]; const sale=sales.find(item=>item.id===saleId); if(!sale||sale.statut==='REMBOURSEE')return; sale.items.forEach(line=>{const product=this.getProduct(line.produitId);if(product){product.stock+=line.qte;this.addMovement({id:Date.now()+line.produitId,date:new Date().toISOString(),type:'RETOUR_CLIENT',produitId:product.id,reference:product.reference,produitNom:product.nom,quantite:line.qte,stockApres:product.stock,motif:'Retour total de la vente',document:sale.numero,utilisateur:localStorage.getItem('username')||'vendeur'});}});sale.statut='REMBOURSEE';this.save('products',[...this.products],this.productsSubject);this.save('sales',sales,this.salesSubject);}
  repayClientCredit(clientId: number, amount: number): void { const clients=[...this.clients];const client=clients.find(item=>item.id===clientId);if(!client)return;client.creditActuel=Math.max(0,client.creditActuel-amount);this.save('clients',clients,this.clientsSubject);}
  receiveOrder(orderId: number): void { const orders = [...this.orders]; const order = orders.find(item => item.id === orderId); if (!order || order.statut === 'RECUE') return; order.lignes.forEach(line => { const remaining = line.quantite - line.quantiteRecue; line.quantiteRecue = line.quantite; const product = this.getProduct(line.produitId); if (product && remaining > 0) { product.stock += remaining; this.addMovement({ id: Date.now() + line.produitId, date: new Date().toISOString(), type: 'RECEPTION', produitId: product.id, reference: product.reference, produitNom: product.nom, quantite: remaining, stockApres: product.stock, motif: 'Réception commande fournisseur', document: order.numero, utilisateur: localStorage.getItem('username') || 'magasinier' }); } }); order.statut = 'RECUE'; this.save('products', [...this.products], this.productsSubject); this.save('orders', orders, this.ordersSubject); }
  reset(): void { ['products', 'clients', 'suppliers', 'sales', 'movements', 'orders'].forEach(key => localStorage.removeItem(this.prefix + key)); this.productsSubject.next(structuredClone(MOCK_PRODUCTS)); this.clientsSubject.next(structuredClone(MOCK_CLIENTS)); this.suppliersSubject.next(structuredClone(MOCK_SUPPLIERS)); this.salesSubject.next(structuredClone(MOCK_SALES)); this.movementsSubject.next(structuredClone(MOCK_MOVEMENTS)); this.ordersSubject.next(structuredClone(MOCK_ORDERS)); }
  private addMovement(movement: StockMovement): void { this.save('movements', [movement, ...this.movements], this.movementsSubject); }
  private load<T>(key: string, fallback: T): T { try { const raw = localStorage.getItem(this.prefix + key); return raw ? JSON.parse(raw) : structuredClone(fallback); } catch { return structuredClone(fallback); } }
  private save<T>(key: string, value: T, subject: BehaviorSubject<T>): void { localStorage.setItem(this.prefix + key, JSON.stringify(value)); subject.next(value); }
}
